// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-cV_ZknwVhBcJh0hl8TPtmEYElTd9REY',
    appId: '1:911222503841:web:b47bf549be6c849ddeb3e0',
    messagingSenderId: '911222503841',
    projectId: 'chatapp-378bd',
    authDomain: 'chatapp-378bd.firebaseapp.com',
    storageBucket: 'chatapp-378bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5bD8VIg4T0zP7ydCKn80b9iFPzgR5j2U',
    appId: '1:911222503841:android:780586f1efbfd334deb3e0',
    messagingSenderId: '911222503841',
    projectId: 'chatapp-378bd',
    storageBucket: 'chatapp-378bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj_68TFzQw0WGuPpa65XKXwh1BKT-YZxg',
    appId: '1:911222503841:ios:0a55b0e23f71a139deb3e0',
    messagingSenderId: '911222503841',
    projectId: 'chatapp-378bd',
    storageBucket: 'chatapp-378bd.appspot.com',
    iosClientId: '911222503841-5j2n4smsr9lipgmebufeg4rmilnnu40f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj_68TFzQw0WGuPpa65XKXwh1BKT-YZxg',
    appId: '1:911222503841:ios:0a55b0e23f71a139deb3e0',
    messagingSenderId: '911222503841',
    projectId: 'chatapp-378bd',
    storageBucket: 'chatapp-378bd.appspot.com',
    iosClientId: '911222503841-5j2n4smsr9lipgmebufeg4rmilnnu40f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
